# Generated by Django 2.2.25 on 2023-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotracking', '0002_renaming_fields_and_adding_referrer_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='days_visited',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
