# Generated by Django 2.2.25 on 2022-01-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Auction for a Month',
                'verbose_name_plural': 'Auctions for a Month',
            },
        ),
        migrations.CreateModel(
            name='AuctionSemester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Auction for a Semester',
                'verbose_name_plural': 'Auctions for a Semester',
            },
        ),
        migrations.CreateModel(
            name='AuctionTrimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Auction for a Trimester',
                'verbose_name_plural': 'Auctions for a Trimester',
            },
        ),
        migrations.CreateModel(
            name='AuctionYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date', models.DateField()),
                ('created', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Auction for a Year',
                'verbose_name_plural': 'Auctions for a Year',
            },
        ),
    ]
